global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mist
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - mist:4242
